import { ChannelType, type Chat, type ChatMember, type Message } from "@/types";

const currentUserId = "user_self";

const members: Record<string, ChatMember> = {
  user_alice: {
    user_id: "user_alice",
    username: "alice",
    global_name: "Alice Wonderland",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Alice",
  },
  user_bob: {
    user_id: "user_bob",
    username: "bob",
    global_name: "Bob Builder",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Bob",
  },
  user_charlie: {
    user_id: "user_charlie",
    username: "charlie",
    global_name: "Charlie",
    avatar: null,
  },
  user_diana: {
    user_id: "user_diana",
    username: "diana",
    global_name: "Diana Prince",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Diana",
  },
  user_self: {
    user_id: currentUserId,
    username: "me",
    global_name: "Current User",
    avatar: null,
  },
};

function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60000).toISOString();
}

export const testChats: Chat[] = [
  {
    id: "chat_dm_unread",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 3,
    last_message: {
      id: "msg_unread",
      chat_id: "chat_dm_unread",
      author_id: "user_alice",
      author: members.user_alice,
      content: "Hey! Are you coming to the meetup tomorrow?",
      created_at: ago(3),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_alice, members.user_self],
  },
  {
    id: "chat_dm_read_other",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "msg_read_other",
    max_read_message_id: "",
    unread_count: 0,
    last_message: {
      id: "msg_read_other",
      chat_id: "chat_dm_read_other",
      author_id: "user_bob",
      author: members.user_bob,
      content: "Thanks for the explanation!",
      created_at: ago(120),
      edited_at: null,
      attachments: [],
      type: "REPLY",
      metadata: {
        referenced_message: {
          id: "msg_self_bob",
          chat_id: "chat_dm_read_other",
          author_id: currentUserId,
          author: members.user_self,
          content: "Let me break it down for you",
          created_at: ago(125),
          edited_at: null,
          attachments: [],
          type: "DEFAULT",
          metadata: null,
        },
      },
    },
    members: [members.user_bob, members.user_self],
  },
  {
    id: "chat_dm_own_not_read",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 0,
    last_message: {
      id: "msg_own_not_read",
      chat_id: "chat_dm_own_not_read",
      author_id: currentUserId,
      author: members.user_self,
      content: "Sent the files, check your email",
      created_at: ago(10),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_alice, members.user_self],
  },
  {
    id: "chat_dm_own_read",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "msg_own_read",
    max_read_message_id: "msg_own_read",
    unread_count: 0,
    last_message: {
      id: "msg_own_read",
      chat_id: "chat_dm_own_read",
      author_id: currentUserId,
      author: members.user_self,
      content: "Sure, I'll send the files over in a bit",
      created_at: ago(60),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_bob, members.user_self],
  },
  {
    id: "chat_saved_messages",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "",
    max_read_message_id: "msg_saved",
    unread_count: 0,
    last_message: {
      id: "msg_saved",
      chat_id: "chat_saved_messages",
      author_id: currentUserId,
      author: members.user_self,
      content: "Remember this idea for later",
      created_at: ago(30),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_self],
  },
  {
    id: "chat_group_42",
    owner_id: "user_self",
    name: "Dev Team",
    description: "Development team chat",
    image: null,
    type: ChannelType.GROUP_DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 42,
    last_message: {
      id: "msg_group_42",
      chat_id: "chat_group_42",
      author_id: "user_diana",
      author: members.user_diana,
      content: "Don't forget to review the PR before EOD!",
      created_at: ago(15),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [
      members.user_alice,
      members.user_bob,
      members.user_charlie,
      members.user_diana,
      members.user_self,
    ],
  },
  {
    id: "chat_group_4242",
    owner_id: "user_alice",
    name: "General",
    description: null,
    image: null,
    type: ChannelType.GROUP_DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 4242,
    last_message: {
      id: "msg_group_4242",
      chat_id: "chat_group_4242",
      author_id: "user_bob",
      author: members.user_bob,
      content: "Has anyone seen the latest deployment notes?",
      created_at: ago(5),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [
      members.user_alice,
      members.user_bob,
      members.user_charlie,
      members.user_diana,
      members.user_self,
    ],
  },
];

const yesterday = 24 * 60;
const fourDaysAgo = 4 * 24 * 60;
const chatId = "chat_group_42";

const dianaMsg: Message = {
  id: "msg_y6",
  chat_id: chatId,
  author_id: "user_diana",
  author: members.user_diana,
  content: "Hey everyone! Ready for the meeting?",
  created_at: ago(yesterday + 55),
  edited_at: null,
  attachments: [],
  type: "DEFAULT",
  metadata: null,
};

export const testMessages: Message[] = [
  {
    id: "msg_o1",
    chat_id: chatId,
    author_id: "user_diana",
    author: members.user_diana,
    content: "Initial planning session was great. Here are the key takeaways from the meeting.",
    created_at: ago(fourDaysAgo + 60),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_o2",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "I've set up the CI/CD pipeline. Should be ready for review by tomorrow.",
    created_at: ago(fourDaysAgo + 55),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_o3",
    chat_id: chatId,
    author_id: "user_diana",
    author: members.user_diana,
    content: "Here's the design system proposal I've been working on",
    created_at: ago(fourDaysAgo + 50),
    edited_at: null,
    attachments: [
      {
        id: "att_img_1",
        message_id: "msg_o3",
        chat_id: chatId,
        filename: "design-system-proposal.png",
        content_type: "image/png",
        size: 2048000,
        storage_key: "https://picsum.photos/seed/proposal/800/600",
        created_at: ago(fourDaysAgo + 50),
      },
    ],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_o4",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "Let me send you the voice notes from the client meeting",
    created_at: ago(fourDaysAgo + 45),
    edited_at: null,
    attachments: [
      {
        id: "att_audio_1",
        message_id: "msg_o4",
        chat_id: chatId,
        filename: "client-meeting-notes.mp3",
        content_type: "audio/mpeg",
        size: 5242880,
        storage_key: "https://example.com/audio.mp3",
        created_at: ago(fourDaysAgo + 45),
      },
    ],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_o5",
    chat_id: chatId,
    author_id: "user_bob",
    author: members.user_bob,
    content: "Attaching the requirements document for review",
    created_at: ago(fourDaysAgo + 40),
    edited_at: null,
    attachments: [
      {
        id: "att_file_1",
        message_id: "msg_o5",
        chat_id: chatId,
        filename: "requirements-v2.pdf",
        content_type: "application/pdf",
        size: 1572864,
        storage_key: "https://example.com/doc.pdf",
        created_at: ago(fourDaysAgo + 40),
      },
      {
        id: "att_file_2",
        message_id: "msg_o5",
        chat_id: chatId,
        filename: "project-assets.zip",
        content_type: "application/zip",
        size: 10485760,
        storage_key: "https://example.com/assets.zip",
        created_at: ago(fourDaysAgo + 40),
      },
    ],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_y1",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(yesterday + 60),
    edited_at: null,
    attachments: [],
    type: "CHAT_CREATE",
    metadata: { chat_name: "General" },
  },
  {
    id: "msg_y2",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(yesterday + 59),
    edited_at: null,
    attachments: [],
    type: "MEMBER_ADD",
    metadata: { user: members.user_bob },
  },
  {
    id: "msg_y3",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(yesterday + 58),
    edited_at: null,
    attachments: [],
    type: "MEMBER_ADD",
    metadata: { user: members.user_charlie },
  },
  {
    id: "msg_y4",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(yesterday + 57),
    edited_at: null,
    attachments: [],
    type: "MEMBER_ADD",
    metadata: { user: members.user_diana },
  },
  {
    id: "msg_y5",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(yesterday + 56),
    edited_at: null,
    attachments: [],
    type: "MEMBER_ADD",
    metadata: { user: members.user_self },
  },
  dianaMsg,
  {
    id: "msg_y7",
    chat_id: chatId,
    author_id: "user_bob",
    author: members.user_bob,
    content: "Morning! Ready when you are",
    created_at: ago(yesterday + 45),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_y8",
    chat_id: chatId,
    author_id: "user_charlie",
    author: members.user_charlie,
    content: "👋 Hey all",
    created_at: ago(yesterday + 40),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_y9",
    chat_id: chatId,
    author_id: "user_diana",
    author: members.user_diana,
    content: "Don't forget to review the latest PR #42",
    created_at: ago(yesterday + 30),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_y10",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "On it. Looks good so far! The CI is passing",
    created_at: ago(yesterday + 25),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_y11",
    chat_id: chatId,
    author_id: "user_diana",
    author: members.user_diana,
    content: "Also, has anyone seen the new mockups?",
    created_at: ago(yesterday + 20),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_y12",
    chat_id: chatId,
    author_id: "user_bob",
    author: members.user_bob,
    content: "Yeah, they're in Figma. I left some notes",
    created_at: ago(yesterday + 15),
    edited_at: null,
    attachments: [],
    type: "REPLY",
    metadata: { referenced_message: dianaMsg },
  },
  {
    id: "msg_t1",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(360),
    edited_at: null,
    attachments: [],
    type: "CHAT_NAME_UPDATE",
    metadata: { new_name: "Dev Team" },
  },
  {
    id: "msg_t2",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "Please check the new designs when you get a chance",
    created_at: ago(300),
    edited_at: null,
    attachments: [
      {
        id: "att_1",
        message_id: "msg_t2",
        chat_id: chatId,
        filename: "screenshot.png",
        content_type: "image/png",
        size: 1048576,
        storage_key: "https://picsum.photos/seed/design/400/300",
        created_at: ago(300),
      },
    ],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t3",
    chat_id: chatId,
    author_id: currentUserId,
    author: members.user_self,
    content: "They look great! The new color palette is much cleaner",
    created_at: ago(240),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t4",
    chat_id: chatId,
    author_id: currentUserId,
    author: members.user_self,
    content: "Left some comments on the homepage flow",
    created_at: ago(180),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t5",
    chat_id: chatId,
    author_id: currentUserId,
    author: members.user_self,
    content: "The onboarding section is much better now",
    created_at: ago(120),
    edited_at: ago(119),
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t6",
    chat_id: chatId,
    author_id: "user_charlie",
    author: members.user_charlie,
    content: "Agreed, nice work team! The animations are smooth",
    created_at: ago(90),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t7",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(60),
    edited_at: null,
    attachments: [],
    type: "MEMBER_REMOVE",
    metadata: { user: members.user_charlie },
  },
  {
    id: "msg_t8",
    chat_id: chatId,
    author_id: "user_alice",
    author: members.user_alice,
    content: "",
    created_at: ago(45),
    edited_at: null,
    attachments: [],
    type: "CHAT_IMAGE_UPDATE",
    metadata: {
      new_image: "https://api.dicebear.com/9.x/notionists/svg?seed=DevTeam",
    },
  },
  {
    id: "msg_t9",
    chat_id: chatId,
    author_id: "user_diana",
    author: members.user_diana,
    content: "Great progress everyone! Let's keep it up 🚀",
    created_at: ago(30),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t10",
    chat_id: chatId,
    author_id: currentUserId,
    author: members.user_self,
    content: "Let me know if there are any changes needed before I finalize everything",
    created_at: ago(5),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t11",
    chat_id: chatId,
    author_id: currentUserId,
    author: members.user_self,
    content: "Actually, one more thing — I updated the deployment script",
    created_at: ago(3),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
  {
    id: "msg_t12",
    chat_id: chatId,
    author_id: currentUserId,
    author: members.user_self,
    content: "Check the env variables in the .env.example file",
    created_at: ago(2),
    edited_at: null,
    attachments: [],
    type: "DEFAULT",
    metadata: null,
  },
];
