import { ChannelType, type Chat, type ChatMember } from "@/types";

const currentUserId = "user_self";

const members: Record<string, ChatMember> = {
  user_alice: {
    user_id: "user_alice",
    username: "alice",
    global_name: "Alice Wonderland",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Alice",
  },
  user_bob: {
    user_id: "user_bob",
    username: "bob",
    global_name: "Bob Builder",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Bob",
  },
  user_charlie: {
    user_id: "user_charlie",
    username: "charlie",
    global_name: "Charlie",
    avatar: null,
  },
  user_diana: {
    user_id: "user_diana",
    username: "diana",
    global_name: "Diana Prince",
    avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=Diana",
  },
  user_self: {
    user_id: currentUserId,
    username: "me",
    global_name: "Current User",
    avatar: null,
  },
};

function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60000).toISOString();
}

export const testChats: Chat[] = [
  {
    id: "chat_dm_unread",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 3,
    last_message: {
      id: "msg_unread",
      chat_id: "chat_dm_unread",
      author_id: "user_alice",
      author: members.user_alice,
      content: "Hey! Are you coming to the meetup tomorrow?",
      created_at: ago(3),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_alice, members.user_self],
  },
  {
    id: "chat_dm_read_other",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "msg_read_other",
    max_read_message_id: "",
    unread_count: 0,
    last_message: {
      id: "msg_read_other",
      chat_id: "chat_dm_read_other",
      author_id: "user_bob",
      author: members.user_bob,
      content: "Thanks for the explanation!",
      created_at: ago(120),
      edited_at: null,
      attachments: [],
      type: "REPLY",
      metadata: {
        referenced_message: {
          id: "msg_self_bob",
          chat_id: "chat_dm_read_other",
          author_id: currentUserId,
          author: members.user_self,
          content: "Let me break it down for you",
          created_at: ago(125),
          edited_at: null,
          attachments: [],
          type: "DEFAULT",
          metadata: null,
        },
      },
    },
    members: [members.user_bob, members.user_self],
  },
  {
    id: "chat_dm_own_not_read",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 0,
    last_message: {
      id: "msg_own_not_read",
      chat_id: "chat_dm_own_not_read",
      author_id: currentUserId,
      author: members.user_self,
      content: "Sent the files, check your email",
      created_at: ago(10),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_alice, members.user_self],
  },
  {
    id: "chat_dm_own_read",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "msg_own_read",
    max_read_message_id: "msg_own_read",
    unread_count: 0,
    last_message: {
      id: "msg_own_read",
      chat_id: "chat_dm_own_read",
      author_id: currentUserId,
      author: members.user_self,
      content: "Sure, I'll send the files over in a bit",
      created_at: ago(60),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_bob, members.user_self],
  },
  {
    id: "chat_saved_messages",
    owner_id: null,
    name: null,
    description: null,
    image: null,
    type: ChannelType.DM,
    last_read_message_id: "",
    max_read_message_id: "msg_saved",
    unread_count: 0,
    last_message: {
      id: "msg_saved",
      chat_id: "chat_saved_messages",
      author_id: currentUserId,
      author: members.user_self,
      content: "Remember this idea for later",
      created_at: ago(30),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [members.user_self],
  },
  {
    id: "chat_group_42",
    owner_id: "user_self",
    name: "Dev Team",
    description: "Development team chat",
    image: null,
    type: ChannelType.GROUP_DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 42,
    last_message: {
      id: "msg_group_42",
      chat_id: "chat_group_42",
      author_id: "user_diana",
      author: members.user_diana,
      content: "Don't forget to review the PR before EOD!",
      created_at: ago(15),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [
      members.user_alice,
      members.user_bob,
      members.user_charlie,
      members.user_diana,
      members.user_self,
    ],
  },
  {
    id: "chat_group_4242",
    owner_id: "user_alice",
    name: "General",
    description: null,
    image: null,
    type: ChannelType.GROUP_DM,
    last_read_message_id: "",
    max_read_message_id: "",
    unread_count: 4242,
    last_message: {
      id: "msg_group_4242",
      chat_id: "chat_group_4242",
      author_id: "user_bob",
      author: members.user_bob,
      content: "Has anyone seen the latest deployment notes?",
      created_at: ago(5),
      edited_at: null,
      attachments: [],
      type: "DEFAULT",
      metadata: null,
    },
    members: [
      members.user_alice,
      members.user_bob,
      members.user_charlie,
      members.user_diana,
      members.user_self,
    ],
  },
];
